### ISSUE TITLE
Determine Cause for Importers Failing Randomly - NRPTI

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#994] opened 2022-09-22 16:37 UTC
**Describe the Bug**
In Prod and in Test, the importers will sometimes fail and will need to be re-run. The reason for failure is unclear.

**Expected Behaviour**
The importers successfully pull the data they're supposed to.

**Actual Behaviour**
On occasion, the importer does not successfully pull the data. 

**Implications**
Created additional work for employees. Bad reputation for application.

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Additional Context**
We need to know what a failure looks like (what messages pop up, what's not happening, etc.)

**Comment by RFK250** [comment] 2023-04-27 22:22
@jakemorr Additional information... This most commonly affects the NRIS-EPD importer, which works by calling the NRIS Web Service applet, which itself was built several years ago as way of exporting NRIS data since NRIS wasn't built with an API. A common reason why the NRIS-EPD importer shows as "failed" is because the NRIS Web Service applet takes too long to run - for whatever reason - and then NRPTI throws a timeout.

I think this ticket is too broad b/c all the importers get their information via (often very different) different means, and the cause of a failure of one importer is not likely going to impact another. There's real rabbit hole potential here. I suggest closing this ticket, and then re-opening a new ticket down the road if and when a specific importer starts to fail consistently.

**Closed** 2023-10-13 16:57 UTC
Labels: Old Bug, Cancelled
