### ISSUE TITLE
Dockerfile Nonexistant Branch Checkout in WALLY

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/NRPTI#948] opened 2022-04-19 23:53 UTC
**Additional context**
/backend/dockerfile.dev has a git checkout command that causes the build to fail because the branch it references does not exist.

**Definition of Done**
- [ ] Remove deprecated git checkout command

**Comment by LolandaE** [comment] 2022-05-16 22:45
Duplicate of [Wally #616]   [https://app.zenhub.com/workspaces/sustainment-team-621fdc6b9ad7010018d8dc2c/issues/bcgov-c/wally/616](url)

**Closed** 2022-05-16 22:47 UTC
Labels: Bug, Ready
